# original version autogenerated by Stepford: https://github.com/garysweaver/stepford

FactoryGirl.define do

  factory :accident do
    sequence(:id)
    date { 2.weeks.ago }
    time { 2.weeks.ago }
    severity 123
    police_response 123
    casualities 123
    lat 1.23
    long 1.23
  end

  factory :attraction do
    sequence(:id)
    type 123
    lat 1.23
    long 1.23
    name 'Test Name'
    description 'Test Description'
    contact_tel 'Test Contact Tel'
    address1 'Test Address1'
    address2 'Test Address2'
    town 'Test Town'
    postcode 'Test Postcode'
  end

  factory :events do
    sequence(:id)
    type 123
    attraction_id 123
    name 'Test Name'
    description 'Test Description'
    start_time { 2.weeks.ago }
    end_time { 2.weeks.ago }
    road_closure_details 'Test Road Closure Details'
  end

  factory :picture do
    sequence(:id)
    url 'Test Url'
    label 'Test Label'
    lat 1.23
    long 1.23
    credit_label 'Test Credit Label'
    credit_url 'Test Credit Url'
  end

  factory :route do
    # after(:create) do |user, evaluator|; FactoryGirl.create_list :route, 2; end # commented to avoid circular reference
    after(:create) do |user, evaluator|; FactoryGirl.create_list :route_point, 2; end # commented to avoid circular reference
    after(:create) do |user, evaluator|; FactoryGirl.create_list :route_review, 2; end # commented to avoid circular reference
    association :original, factory: :route
    user
    sequence(:id)
    created_by 123
    name 'Test Name'
    start_lat 1.23
    start_long 1.23
    end_lat 1.23
    end_long 1.23
    calculated_total_time 123
    total_distance 1.23
    last_used { 2.weeks.ago }
    mode 123
    safety 123
    difficulty 123
    start_picture_id 123
    end_picture_id 123
    start_time { 2.weeks.ago }
    end_time { 2.weeks.ago }
    rating 123
    total_time 123
  end

  factory :route_point do
    route
    sequence(:id)
    lat 1.23
    long 1.23
    preceding_route_point_id 123
    next_route_point_id 123
    altitude 1.23
    on_road true
    street_name 'Test Street Name'
    street_postcode 'Test Street Postcode'
    time { 2.weeks.ago }
  end

  factory :route_review do
    route
    user
    sequence(:id)
    comment 'Test Comment'
    safety_rating 123
    difficulty_rating 123
    environment_rating 123
  end

  factory :user do
    after(:create) do |user, evaluator|; FactoryGirl.create_list :route, 2; end # commented to avoid circular reference
    after(:create) do |user, evaluator|; FactoryGirl.create_list :route_review, 2; end # commented to avoid circular reference
    sequence(:id)
    sequence(:email) do |n|; "person#{n}@example.com"; end
    encrypted_password ''
    reset_password_token 'Test Reset Password Token'
    reset_password_sent_at { 2.weeks.ago }
    remember_created_at { 2.weeks.ago }
    sign_in_count 0
    current_sign_in_at { 2.weeks.ago }
    last_sign_in_at { 2.weeks.ago }
    current_sign_in_ip 'Test Current Sign In Ip'
    last_sign_in_ip 'Test Last Sign In Ip'
    first_name 'Test First Name'
    last_name 'Test Last Name'
    profile_picture 'Test Profile Picture'
    gender 123
    dob { 2.weeks.ago }
    authentication_token 'Test Authentication Token'
  end

  factory :user_response do
    sequence(:id)
    user_id 123
    usage_per_week 123
    usage_type 123
    usage_reason 123
  end

  factory :weather do
    after(:create) do |user, evaluator|; FactoryGirl.create_list :weather_period, 2; end # commented to avoid circular reference
    sequence(:id)
    date { 2.weeks.ago }
    sunset { 2.weeks.ago }
    sunrise { 2.weeks.ago }
  end

  factory :weather_period do
    weather
    sequence(:id)
    start_time { 2.weeks.ago }
    end_time { 2.weeks.ago }
    precipitation_type 123
    precipitation_level 123
    wind_speed 123
    wind_direction 123
    pollen_count 123
    uv_level 123
  end

end
